name: swip_core
description: SWIP Core - Scoring engine for the Synheart Wellness Impact Protocol
version: 0.1.0+4
homepage: https://github.com/synheart-ai/
repository: https://github.com/synheart-ai/swip-core

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/models/extratrees_wrist_all_v1_0.onnx
    - assets/models/extratrees_wrist_all_v1_0.meta.json
